### ISSUE TITLE
Character Portraits with varying expressions for *cutscenes*/dialogue

### ISSUE THREAD

**Issue by meatsupplies** [digocorbellini/EGaDS-Open-Project#2]
![image](https://user-images.githubusercontent.com/107739078/174420995-592838a1-1a27-4e04-8440-b3bc077e88f9.png)

To introduce the story and bring up mono/dialogue, could i draw & add character portraits of the MC with different expressions?

**Comment by digocorbellini** [comment]
I like this idea! Great way to display expositional content and a great way to better show off the characters.

I'd like to put this on the Trello board, but I might need more specific details on what exactly would be need to be made for this feature to work.

How many character portraits/expressions were you thinking about making? Would this include art for the dialogue box?

**Comment by meatsupplies** [comment]
I was thinking about making 5 expressions (tired(default), determined, weary, surprised, fired up) but I'm open to drawing more if need be.

maq was interested in helping out with this so art for the dialogue boxes would be included

**Comment by digocorbellini** [comment]
Ok that sounds great! I'll add these expression and the dialogue box to the trello board and mark the tasks as claimed.
