### ISSUE TITLE
Story/Lore Ideas for the Game

### ISSUE THREAD

**Issue by Cashman0604** [digocorbellini/EGaDS-Open-Project#5]
Based on what crab-milk posted, I had an idea for setting up the environment as well as the general plot.

There's a giant corporate building; half is above Earth's surface, and the other half is below. The top half is the offices of Heaven, and the bottom half is Hell. You are an angel at the bottom of the totem pole, not even having earned wings. Tired of being bottom of the barrel, our character decides to kill Satan, located at the very bottom of the tower. This task would be enough to promote anyone to Archangel, the highest position nigh of God. With it comes the comfort of respect and luxury, a reward tempting enough for anyone if not for the fear of death. Along the journey, you find both Angelic and Demonic powerups (these could be just thematic powers, or they could be used as a system where they interact with each other in certain ways [i.e. the more Angelic powers you have the less powerful the Demonic ones are, and vice versa {This is probably too much and doesn't fit well with the genre, but it's just an idea}]). The reason Angelic powerups appear in the Hell offices is that other Angels have tried to kill Satan, but have failed, leaving their powers behind for others to reclaim. For the Demonic, obviously, they are there since it's the Hell offices.

As far as death, I think it would be fun if it were canonical. So every time you die, your character is respawned in the Heaven offices and had actually died, so Angels upon death are reborn in Heaven offices. Or we could say the character has some item of personal significance that pulls them out of death situations but strips them of their abilities when doing so. This would also allow for a shop to be at the very beginning of the game without it being strange, so if someone had a certain currency, they could go in with an ability already. Otherwise, we just do non-canonical death, but I think it would be really easy to explain in the game a canonical reason.

For transitioning between floors, it becomes more corrupted because you are descending deeper into Hell. On that note as well, a reason for the shifting floor plans could be that Satan caused them to be constantly changing to deter Angels from crusading into Hell.

Also for all the designs, enemy or friendly, an explanation for more human-looking people is that the closer your assigned floor is to Earth's surface, the more you look like a normal human. That would be another explanation for why the main character doesn't look like an angel, they just work on a really down to Earth floor.

I think this covers most of the topics, but if there are any questions about this lmk.

**Comment by jamesouyang2003** [comment]
Related to #4 
Thanks for the idea! I really like your idea about death being canonical- it fits with the rogue like genre a lot.

Just for future reference, try to keep ideas related to another post in the comment thread of the original post so everything here stays organized. I’ll be closing this post here, but feel free to repost your idea as a comment in the other thread!
